service: serverless-backend

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true